Safira.App/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Safira.App.Extensions;
using Safira.Domain.Enums;
using Safira.Domain.IServices;
using Safira.Domain.Models;
using Safira.Domain.Models.Product;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Safira.App.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        #region Fields & Ctor

        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly ApplicationSettings _appSettings;

        public ProductController(
            IProductService productService,
            ICategoryService categoryService,
            ApplicationSettings applicationSettings)
        {
            _productService = productService;
            _categoryService = categoryService;
            _appSettings = applicationSettings;
        }

        #endregion

        #region Action Methods

        public async Task<ActionResult> Index()
        {
            var model = await GetListViewModel(new ProductFilteringModel());
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            var model = new ProductViewModel
            {
                Status = StatusEnum.Active.ToEnumSelectList(null, string.Empty),
                Categories = await _categoryService.GetSelectListAsync(),
                Types = ProductTypeEnum.Trend.ToEnumSelectList(null, string.Empty)
            };
            return View(model);
        }

        public async Task<IActionResult> Edit(long id)
        {
            var model = new ProductViewModel
            {
                Status = StatusEnum.Active.ToEnumSelectList(null, string.Empty),
                Categories = await _categoryService.GetSelectListAsync(),
                Types = ProductTypeEnum.Trend.ToEnumSelectList(null, string.Empty)
            };

            var product = await _productService.GetByIdAsync(id);
            if (product != null)
            {
                model.Id = product.Id;
                model.Name = product.Name;
                model.Description = product.Description;
                model.Processing = product.Processing;
                model.Useful = product.Useful;
                model.StatusId = product.StatusId;
                model.CategoryId = product.CategoryId;
                model.TypeId = product.TypeId;
                model.SaleUp = product.SaleUp;
                model.CreatedDate = product.CreatedDate;
                model.Price = product.Price;
                model.OldPrice = product.OldPrice;
                model.Files = product.Files;
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Save(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _productService.SaveAsync(model);
                return JsonResult(result);
            }
            return JsonError("Invalid model.");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _productService.DeleteAsync(id);
            return JsonResult(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetList(ProductFilteringModel filtering)
        {
            return PartialView("_ProductList", await GetListViewModel(filtering));
        }

        #endregion

        #region Utilities Methods
        private async Task<ProductListViewModel> GetListViewModel(ProductFilteringModel filtering)
        {
            var products = await _productService.GetListAsync(filtering, true);
            var categories = await _categoryService.GetSelectListAsync("Chọn nhóm");
            return new ProductListViewModel(products, filtering)
            {
                Categories = categories,
                PageSizeOptions = _appSettings.PageSizeOptions.ToDicSelectList(filtering.PageSize.ToString(), false),
            };
        }

        #endregion
    }
}

Safira.App/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Safira.Domain.IServices;
using Safira.Domain.Models;

namespace Safira.App.Controllers
{
    public class FileController : Controller
    {
        #region Fields & Ctor

        private readonly IFileService _fileService;

        public FileController(IFileService fileService) => _fileService = fileService;

        #endregion

        #region Action Methods

        public async Task<FileResult> Get(long id)
        {
            var img = await _fileService.GetByIdAsync(id);
            return File(img.Binary, img.MimeType);
        }

        public async Task<IActionResult> Download(long id)
        {
            var img = await _fileService.GetByIdAsync(id);
            return File(new MemoryStream(img.Binary), img.MimeType, img.SeoFileName);
        }

        #endregion
    }
}

Safira.App/Controllers/OrderController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Safira.Domain.IServices;
using Safira.Domain.Models;
using Safira.Domain.Models.Order;
using Safira.Domain.Models.Product;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Safira.App.Controllers
{
    public class OrderController : ShoppingController
    {
        #region Fields & Ctor

        private readonly IOrderService _orderService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailService _emailService;
        private readonly IEmailSender _emailSender;
        private readonly Messages _message;
        private readonly ApplicationSettings _appSettings;

        public OrderController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IProductService productService,
            ICartService cartService,
            IOrderService orderService,
            IEmailService emailService,
            IEmailSender emailSender,
            Messages messages,
            ApplicationSettings appSettings) 
            : base(userManager, signInManager, productService, cartService)
        {
            _orderService = orderService;
            _userManager = userManager;
            _signInManager = signInManager;
            _emailService = emailService;
            _emailSender = emailSender;
            _message = messages;
            _appSettings = appSettings;
        }

        #endregion

        #region Methods

        public IActionResult Cart()
        {
            var model = GetCart();
            return View(model);
        }

        [HttpGet]
        public IActionResult GetCartList()
        {
            var model = GetCart();
            return PartialView("_CartList", model);
        }

        public async Task<IActionResult> Checkout()
        {
            var product = GetCart();
            var model = new CheckoutViewModel()
            {
                Products = product
            };
            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);
                model.Email = user.UserName;
                model.FirstName = user.FirstName;
                model.LastName = user.LastName;
                model.PhoneNumber = user.PhoneNumber;
                model.Address = user.Address;
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckoutViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Products = GetCart();
                var result = await _orderService.SaveOrder(model);
                if (result.ResultType == Domain.Result.ResultType.Success)
                {
                    var order = await _orderService.GetByIdAsync(result.Value);
                    await SendEmail(order);
                    return RedirectToAction(nameof(Thankyou));
                }
                ModelState.AddModelError("", result.Message);
            }
            else
                ModelState.AddModelError("", _message.Email_Have_Been_Exist);

            return View(model);
        }

        public IActionResult Thankyou()
        {
            ClearCart();
            return View();
        }

        public IActionResult WishList()
        {
            var model = GetFavourites();
            return View(model);
        }

        [HttpGet]
        public IActionResult GetWishList()
        {
            var model = GetFavourites();
            return PartialView("_WishList", model);
        }

        #endregion

        private async Task SendEmail(CheckoutViewModel model)
        {
            var content = GetEmailContent(model.Products);
            var email = new EmailModel
            {
                Subject = $"Đơn hàng {model.OrderNumber}",
                Content = content,
                RecipientEmail = model.Email,
                RecipientName = model.FullName,
                OrderId = model.Id
            };
            var result = await _emailService.SaveAsync(email);
            if(result.ResultType == Domain.Result.ResultType.Success)
            {
                //Send email to customer
                await _emailSender.SendEmailAsync(email.RecipientEmail, email.Subject, email.Content);

                //Send email to admin
                await _emailSender.SendEmailAsync(_appSettings.AdminEmails.Split(",").ToList(), email.Subject, email.Content);
            }
        }

        private string GetEmailContent(List<ProductCartViewModel> products)
        {
            var content = new StringBuilder();
            foreach(var item in products)
            {
                var sub = @$"<tr style='page-break-inside: avoid;'>
							<td width='204' align='center' style='border-top: 1px solid #000; padding: 13px 0;'>
								<strong style='font-family: Arial, sans-serif; font-size: 13px;'>
									[PRODUCT_NAME]
								</strong>
							</td>
							<td colspan='2' style='border-left: 1px solid #000; border-top: 1px solid #000; padding: 13px 15px; '>
								<span style='font-family: Arial, sans-serif; font-size: 13px;'>
									<strong>[PRODUCT_PRICE]</strong> x <strong>[PRODUCT_QUANTITY]</strong>
								</span>
							</td>
							<td colspan='3' style='border-left: 1px solid #000; border-top: 1px solid #000; padding: 13px 15px; '>
								<span style='font-family: Arial, sans-serif; font-size: 13px; white-space: nowrap;'>
									<strong>[PRODUCT_TOTAL]</strong>
								</span>
							</td>
						</tr>";
                content.Append(sub.Replace("[PRODUCT_NAME]", item.Name)
                    .Replace("[PRODUCT_PRICE]", item.Price.ToString("C0", System.Globalization.CultureInfo.CurrentCulture))
                    .Replace("[PRODUCT_QUANTITY]", item.Quantity.ToString())
                    .Replace("[PRODUCT_TOTAL]", (item.Quantity * item.Price).ToString("C0", System.Globalization.CultureInfo.CurrentCulture)));
            }

            var subTotal = @"<tr style='page-break-inside: avoid;'>
							<td colspan='3' width='104' align='center' style='border-top: 1px solid #000; padding: 13px 0;'>
								<strong style='font-family: Arial, sans-serif; font-size: 13px;'>
									Tổng cộng
								</strong>
							</td>
							<td colspan='3' style='border-left: 1px solid #000; border-top: 1px solid #000; padding: 13px 15px; '>
								<span style='font-family: Arial, sans-serif; font-size: 13px; white-space: nowrap;'>
									<strong>[ORDER_TOTAL]</strong>
								</span>
							</td>
						</tr>";
            content.Append(subTotal.Replace("[ORDER_TOTAL]", products.Sum(t => t.Price * t.Quantity).ToString("C0", System.Globalization.CultureInfo.CurrentCulture)));
            var body = @"<!DOCTYPE html>
<html>
<head>
    <meta http-equiv='Content-Type' content='text/html charset=UTF-8' />
</head>
<body style='margin: 0;'>
    <div style='font-family: Arial, sans-serif; font-size: 13px; color: #000;width: 650px; margin: 0 auto;'>
        <table border='0' align='center' cellpadding='0' cellspacing='0' style='width: 650px; margin: 0 auto; border-spacing: 0; background-color: white;'>
            <tr>
                <td>
                    <p style='font-family: Arial, sans-serif; font-size: 14px; line-height: 20px; margin: 0 0 20px 0;'>
                        <strong>Xin chào,</strong>
                    </p>
                    <p style='font-family: Arial, sans-serif; font-size: 14px;line-height: 20px; margin: 0 0 10px 0;'>
                        Cảm ơn bạn đã tin tưởng và ủng hộ chúng tôi. <br />
                        Chúng tôi sẽ liên hệ với bạn để xác nhận đơn hàng.
                    </p>
                    <p style='font-family: Arial, sans-serif; font-size: 14px;line-height: 20px; margin: 0 0 35px 0;'>
                        Nếu bạn có gì muốn tìm hiểu thêm, hãy liên hệ tới chúng tôi:
                        <a href='mailto:operationvn@ohmyhotel.com' style='color: #000; text-decoration: none'><span style='text-decoration: underline;'>admin@choquehuong.vn</span></a>
                    </p>
                </td>
            </tr>
            <tr>
                <td>
					<table border='0' cellpadding='0' cellspacing='0' style='height: 100%; width: 100%; border-spacing: 0; padding: 0; border-collapse: collapse; border: 1px solid #000;'>
						<tr style='page-break-inside: avoid;'>
							<td colspan='2' bgcolor='#f2f2f2' align='left' style='border-top: 1px solid #000; height: 40px; padding-left: 15px;'>
								<strong style='font-family: Arial, sans-serif; font-size: 14px;'>
								Đơn hàng
								</strong>
							</td>
							<td bgcolor='#f2f2f2' colspan='4' align='right' style='border-top: 1px solid #000; padding-right: 15px; '>
								
							</td>
						</tr>
						[CONTENT_EMAIL]
					</table>
                                        
				</td>
            </tr>
			<tr>
                <td align='center' style='font-family: Arial, sans-serif; color: #555; padding-bottom: 20px'></td>
            </tr>
            <tr>
                <td align='center' style='font-family: Arial, sans-serif; color: #555; padding-bottom: 10px'>Copyright &copy; choquehuong.vn</td>
            </tr>
        </table>
    </div>
</body>
</html>";
            return body.Replace("[CONTENT_EMAIL]", content.ToString());
        }
    }
}

Safira.App/Views/Product/Index.cshtml
@model Safira.Domain.Models.Product.ProductModel;
@{
    ViewData["Title"] = "Chi tiết sản phẩm";
}

<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <h3>Sản phẩm</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<partial name="_ProductDetail" model="Model" />

<partial name="_RelatedProduct" model="Model" />

<partial name="~/Views/Home/_QuickView.cshtml" />

<script src="~/frontend/js/pages/shared.js" asp-append-version="true"></script>
<script src="~/frontend/js/pages/product.js" asp-append-version="true"></script>
<script type="text/javascript">
     $(document).ready(function () {
         GeneralModule.config({
             quickViewUrl: '@Url.Action("QuickView", "Product")',
             addToCartUrl: '@Url.Action("AddToCart", "Product")',
             goToOrderUrl: '@Url.Action("GoToOrder", "Product")',
             goToCheckoutUrl: '@Url.Action("CheckOut", "Order")',
             removeOutCartUrl: '@Url.Action("RemoveOutCart", "Product")',
             addToFavouriteUrl: '@Url.Action("AddToFavourite", "Product")',
             getFavouriteUrl: '@Url.Action("GetFavourite", "Product")'
        });
         ProductModule.config({
         });
     });
</script>

Safira.App/Views/Product/_AddReview.cshtml
@model Safira.Domain.Models.Product.ReviewModel;


<form asp-action="AddReview" asp-controller="Product" method="POST" data-ajax="true"
      ata-ajax-mode="Replace" data-ajax-update="#dev-temp-content"
      data-ajax-begin="GeneralModule.OnAddReviewBegin" data-ajax-complete="GeneralModule.OnAddReviewComplete">
    <div class="hidden" id="dev-temp-content"></div>
    @*<div class="comment_title">
        <h2>Thêm đánh giá </h2>
        <p>Địa chỉ email của bạn sẽ không được công bố. Các trường bắt buộc được đánh dấu * </p>
    </div>*@
    <div class="product_ratting mb-10">
        <h3>Đánh giá của bạn</h3>
        <ul>
            <li><a href="#"><i class="icon-star"></i></a></li>
            <li><a href="#"><i class="icon-star"></i></a></li>
            <li><a href="#"><i class="icon-star"></i></a></li>
            <li><a href="#"><i class="icon-star"></i></a></li>
            <li><a href="#"><i class="icon-star"></i></a></li>
        </ul>
    </div>
    <div class="product_review_form">
        <div class="row">
            <input type="hidden" asp-for="ProductId" />
            <div class="col-12">
                <label asp-for="Content">Nội dung <span class="required">(*)</span></label>
                <textarea asp-for="Content"></textarea>
                <span asp-validation-for="Content"></span>
            </div>
            <div class="col-lg-6 col-md-6">
                <label asp-for="FullName">Tên <span class="required">(*)</span></label>
                <input asp-for="FullName" type="text">
                <span asp-validation-for="FullName"></span>
            </div>
            <div class="col-lg-6 col-md-6">
                <label asp-for="Email">Email <span class="required">(*)</span></label>
                <input asp-for="Email" type="text">
                <span asp-validation-for="Email"></span>
            </div>
        </div>
        <button type="submit">Gởi đánh giá</button>
    </div>
</form>

Safira.App/Views/Product/_QuickView.cshtml
@model Safira.Domain.Models.Product.ProductModel;

<div class="row">
    <div class="col-lg-5 col-md-5 col-sm-12">
        <div class="modal_tab">
            <div class="tab-content product-details-large">
                <div class="tab-pane fade show active" id="tab1" role="tabpanel">
                    <div class="modal_tab_img dev-large-image-container">
                        <img src="@Model.ImageUrls.First()" alt="big-1" />
                    </div>
                </div>
            </div>
            <div class="modal_tab_button">
                <ul class="nav product_navactive owl-carousel owl-loaded owl-drag" role="tablist">
                    <div class="owl-stage-outer">
                        <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s;">
                            @foreach (var file in Model.ImageUrls)
                            {
                                <div class="owl-item">
                                    <li>
                                        <a class="nav-link active dev-show-large-image" data-picture-id="@Model.Id" href="javascript:void(0)"><img src="@file" alt=""></a>
                                    </li>
                                </div>
                            }
                        </div>
                    </div>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-7 col-md-7 col-sm-12">
        <div class="modal_right">
            <div class="modal_title mb-10">
                <h2 class="product_name"><a asp-controller="Product" asp-action="Index" asp-route-id="@Model.Id">@Model.Name</a></h2>
            </div>
            <div class="modal_price mb-10">
                <span class="new_price">@Model.Price.ToString("C0", System.Globalization.CultureInfo.CurrentCulture)</span>
                @if (Model.OldPrice.HasValue)
                {
                    <span class="old_price">@Model.OldPrice.Value.ToString("C0", System.Globalization.CultureInfo.CurrentCulture)</span>
                }
            </div>
            <div class="mb-10">
                <span class="mass">Khối lượng: 1kg</span>
            </div>
            <div class="modal_description mb-15">
                <p>@Html.Raw(Model.Useful)</p>
            </div>
            <div class="variants_selects">
                <div class="modal_add_to_cart">
                    <form>
                        <input id="dev-add-to-cart-number" min="1" max="100" value="1" type="number">
                        <button class="button dev-add-to-cart" type="button" data-product-id="@Model.Id" data-title=" Thêm vào giỏ hàng"><span class="lnr lnr-cart"></span> Thêm vào giỏ hàng</button>
                        <button class="button btn-order dev-go-to-order" type="button" data-product-id="@Model.Id" data-title=" Đặt hàng"><i class="fa fa-sign-in"></i> Đặt hàng</button>
                    </form>
                </div>
            </div>
            <div class="product_d_action">
                <div class="note">
                    <i>Do đặc tính sản phẩm nên trọng lượng thực tế có thể chênh lệch so với số lượng bạn đặt hàng. Chúng tôi sẽ xác nhận với bạn khi có sự thay đổi</i>
                </div>
            </div>
            <div class="modal_social">
                <h2>Chia sẽ</h2>
                <ul>
                    <li class="facebook"><a class="dev-share-to-facebook" href="javascript:void(0)" data-product-id="@Model.Id" data-file-id="@Model.Files[0].Id"><i class="fa fa-facebook"></i></a></li>
                    <li class="twitter disabled"><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                    <li class="pinterest disabled"><a href="javascript:void(0)"><i class="fa fa-pinterest"></i></a></li>
                    <li class="google-plus disabled"><a href="javascript:void(0)"><i class="fa fa-google-plus"></i></a></li>
                    <li class="linkedin disabled"><a href="javascript:void(0)"><i class="fa fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

Safira.App/Views/Product/_RelatedProduct.cshtml
@model Safira.Domain.Models.Product.ProductModel;

<section class="product_area related_products">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section_title">
                    <h2>Sản phẩm tương tự</h2>
                </div>
            </div>
        </div>
        <form id="dev-related-product-form" asp-action="GetRelatedProduct" asp-route-id="@Model.CategoryId" asp-controller="Product" data-ajax="true" method="get"
              data-ajax-mode="Replace" data-ajax-update="#dev-related-product-container"
              data-ajax-begin="ProductModule.OnAjaxBegin" data-ajax-complete="ProductModule.OnAjaxComplete">
            <div class="row" id="dev-related-product-container">
            </div>
        </form>
        
    </div>
</section>

Safira.App/Views/Product/_RelatedProductList.cshtml
@model List<Safira.Domain.Models.Product.ProductModel>;

<div class="col-12">
    <div class="product_carousel product_column5 owl-carousel owl-loaded owl-drag">
        <div class="owl-stage-outer">
            <div class="owl-stage" style="transform: translate3d(-1160px, 0px, 0px); transition: all 0s ease 0s; width: 3712px;">
                @for(var i=0; i<Model.Count; i++)
                {
                    var item = Model[i];
                    <div class="owl-item" style="width: 212px; margin-right: 20px;">
                        <article class="single_product">
                            <figure>
                                <div class="product_thumb">
                                    <a class="primary_img" href="/san-pham/@item.Id/@item.Name.ToLower()">
                                        <img src="@(item.ImageUrls.Any() ? item.ImageUrls.First() : "")" alt="">
                                    </a>
                                    <a class="secondary_img" href="/san-pham/@item.Id/@item.Name.ToLower()">
                                        <img src="@(item.ImageUrls.Any() && item.ImageUrls.Count > 1 ? item.ImageUrls[1] : "")" alt="">
                                    </a>
                                    <div class="label_product">
                                        <span class="label_sale">Sale</span>
                                        <span class="label_new">New</span>
                                    </div>
                                    <partial name="~/Views/Home/_GrpAction.cshtml" model="item" />
                                </div>
                                <figcaption class="product_content">
                                    <h4 class="product_name"><a href="/san-pham/@item.Id/@item.Name.ToLower()">@item.Name</a></h4>
                                    <div class="price_box">
                                        <span class="current_price">@item.Price.ToString("C0", System.Globalization.CultureInfo.CurrentCulture)</span>
                                        @if (item.OldPrice.HasValue)
                                        {
                                            <span class="old_price">@item.OldPrice.Value.ToString("C0", System.Globalization.CultureInfo.CurrentCulture)</span>
                                        }
                                    </div>
                                </figcaption>
                            </figure>
                        </article>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Safira.App/Views/Product/_Review.cshtml
@model Safira.Domain.Models.Product.ProductModel;

    <div class="reviews_wrapper">
        <form asp-action="GetReviewList" asp-controller="Product" method="POST" data-ajax="true"
              ata-ajax-mode="Replace" data-ajax-update="#dev-review-list-container" id="dev-review-list-form"
               data-ajax-complete="GeneralModule.OnGetReviewListComplete">
            <input type="hidden" name="id" value="@Model.Id" />
            <div id="dev-review-list-container">
                <partial name="_ReviewList" model="Model.Reviews" />
            </div>
        </form>
        <partial name="_AddReview" model="new Safira.Domain.Models.Product.ReviewModel() { ProductId = Model.Id }" />
    </div>

Safira.App/Views/Product/_ReviewList.cshtml
@model List<Safira.Domain.Models.Product.ReviewModel>

@foreach (var review in Model)
{
    <input type="hidden" name="dev-review-number" value="@Model.Count" />
    <div class="reviews_comment_box">
        <div class="comment_thmb">
            <img src="~/frontend/img/avatar.png" alt="">
        </div>
        <div class="comment_text">
            <div class="reviews_meta">
                <div class="star_rating">
                    <ul>
                        <li><a href="#"><i class="icon-star"></i></a></li>
                        <li><a href="#"><i class="icon-star"></i></a></li>
                        <li><a href="#"><i class="icon-star"></i></a></li>
                        <li><a href="#"><i class="icon-star"></i></a></li>
                        <li><a href="#"><i class="icon-star"></i></a></li>
                    </ul>
                </div>
                <p><strong>@review.FullName - </strong> <span class="comment-date">@review.CreatedDate.ToString("dd, MMMM, yyyy")</span></p>
                <span>@review.Content</span>
            </div>
        </div>
    </div>
}

Safira.App/Views/Product/_ShoppingCart.cshtml
@model List<Safira.Domain.Models.Product.ProductCartViewModel>
<a href="javascript:void(0)"><span class="lnr lnr-cart"></span><span class="item_count">@Model.Count</span></a>
@if (Model.Any())
{
    <div class="mini_cart">
        <div class="cart_gallery">
            @foreach (var item in Model)
            {
                <div class="cart_item">
                    <div class="cart_img">
                        <a href="/san-pham/@item.ProductId">
                            <img src="@item.ImageUrl" alt=""/>
                            @*<img src="@Url.Action("Get", "File", new { id = item.PictureId })" alt="">*@
                        </a>
                    </div>
                    <div class="cart_info">
                        <a href="/san-pham/@item.ProductId">@item.Name</a>
                        <p>@item.Quantity x <span> @item.Price.ToString("C0", System.Globalization.CultureInfo.CurrentCulture) </span></p>
                    </div>
                    <div class="cart_remove">
                        <a href="javascript:void(0)" class="dev-remove-out-cart" data-product-id="@item.ProductId"><i class="icon-x"></i></a>
                    </div>
                </div>
            }
        </div>
        <div class="mini_cart_table">
            <div class="cart_table_border">
                <div class="cart_total mt-10">
                    <span>Tổng cộng:</span>
                    <span class="price">@Model.Sum(t => t.Price * t.Quantity).ToString("C0", System.Globalization.CultureInfo.CurrentCulture)</span>
                </div>
            </div>
        </div>
        <div class="mini_cart_footer">
            <div class="cart_button">
                <a asp-controller="Order" asp-action="Cart"><i class="fa fa-shopping-cart"></i> Giỏ hàng</a>
            </div>
            <div class="cart_button">
                <a asp-controller="Order" asp-action="Checkout"><i class="fa fa-sign-in"></i> Đặt hàng</a>
            </div>
        </div>
    </div>
}