Safira.App/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Safira.App.Extensions;
using Safira.Domain.IServices;
using Safira.Domain.Models;
using Safira.Domain.Models.Blog;

namespace Safira.App.Controllers
{
    public class BlogController : BaseController
    {
        #region Fields & Ctor

        private readonly IBlogReviewService _reviewService;
        private readonly IBlogService _blogService;
        private readonly ApplicationSettings _appSettings;

        public BlogController(
            IBlogReviewService blogReviewService,
            IBlogService blogService,
            ApplicationSettings applicationSettings)
        {
            _reviewService = blogReviewService;
            _blogService = blogService;
            _appSettings = applicationSettings;
        }


        #endregion
        public async Task<IActionResult> Index(int id)
        {
            var filtering = new BlogFilteringModel
            {
                CategoryId = id,
                PageSize = 12
            };
            var model = await GetListViewModel(filtering);
            return View(model);
        }

        public async Task<IActionResult> Detail(int id = 1, string name = "")
        {
            var model = await _blogService.GetByIdAsync(id);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetBlogList(BlogFilteringModel filtering)
        {
            return PartialView("_BlogList", await GetListViewModel(filtering));
        }

        [HttpPost]
        public async Task<IActionResult> AddReview(BlogReviewModel model)
        {
            var result = new Domain.Result.Result<int>()
            {
                ResultType = Domain.Result.ResultType.Error
            };
            if (ModelState.IsValid)
            {
                result = await _reviewService.SaveAsync(model);
            }
            return JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> GetReviewList(long id)
        {
            var model = await _reviewService.GetListAsync(id);
            return PartialView("_ReviewList", model);
        }

        [HttpPost]
        public async Task<IActionResult> GetRecentReviewList()
        {
            var model = await _reviewService.GetRecentListAsync();
            return PartialView("_RecentReviewList", model);
        }

        [HttpPost]
        public async Task<IActionResult> GetRelatedBlogList(int id, int categoryId)
        {
            var products = await _blogService.GetAllAsync(categoryId);
            if (products.Any())
            {
                //products = products.Where(t => t.Id != id).OrderByDescending(t => t.ModifiedDate).Take(6).ToList();
                products = products.OrderByDescending(t => t.ModifiedDate).Take(6).ToList();
            }
            return PartialView("_RelatedBlogList", products);
        }

        [HttpPost]
        public async Task<IActionResult> GetRecentBlogList()
        {
            var products = await _blogService.GetRecentAsync();
            
            return PartialView("_RecentBlogList", products);
        }

        private async Task<BlogListViewModel> GetListViewModel(BlogFilteringModel filtering)
        {
            filtering.PageSize = _appSettings.DefaultPageSize;
            var products = await _blogService.GetListAsync(filtering);
            return new BlogListViewModel(products, filtering)
            {
                PageSizeOptions = _appSettings.PageSizeOptions.ToDicSelectList(filtering.PageSize.ToString(), false),
            };
        }
    }
}

Safira.App/Controllers/OrderController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Safira.Domain.IServices;
using Safira.Domain.Models;
using Safira.Domain.Models.Order;
using Safira.Domain.Models.Product;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Safira.App.Controllers
{
    public class OrderController : ShoppingController
    {
        #region Fields & Ctor

        private readonly IOrderService _orderService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailService _emailService;
        private readonly IEmailSender _emailSender;
        private readonly Messages _message;
        private readonly ApplicationSettings _appSettings;

        public OrderController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IProductService productService,
            ICartService cartService,
            IOrderService orderService,
            IEmailService emailService,
            IEmailSender emailSender,
            Messages messages,
            ApplicationSettings appSettings) 
            : base(userManager, signInManager, productService, cartService)
        {
            _orderService = orderService;
            _userManager = userManager;
            _signInManager = signInManager;
            _emailService = emailService;
            _emailSender = emailSender;
            _message = messages;
            _appSettings = appSettings;
        }

        #endregion

        #region Methods

        public IActionResult Cart()
        {
            var model = GetCart();
            return View(model);
        }

        [HttpGet]
        public IActionResult GetCartList()
        {
            var model = GetCart();
            return PartialView("_CartList", model);
        }

        public async Task<IActionResult> Checkout()
        {
            var product = GetCart();
            var model = new CheckoutViewModel()
            {
                Products = product
            };
            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);
                model.Email = user.UserName;
                model.FirstName = user.FirstName;
                model.LastName = user.LastName;
                model.PhoneNumber = user.PhoneNumber;
                model.Address = user.Address;
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckoutViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Products = GetCart();
                var result = await _orderService.SaveOrder(model);
                if (result.ResultType == Domain.Result.ResultType.Success)
                {
                    var order = await _orderService.GetByIdAsync(result.Value);
                    await SendEmail(order);
                    return RedirectToAction(nameof(Thankyou));
                }
                ModelState.AddModelError("", result.Message);
            }
            else
                ModelState.AddModelError("", _message.Email_Have_Been_Exist);

            return View(model);
        }

        public IActionResult Thankyou()
        {
            ClearCart();
            return View();
        }

        public IActionResult WishList()
        {
            var model = GetFavourites();
            return View(model);
        }

        [HttpGet]
        public IActionResult GetWishList()
        {
            var model = GetFavourites();
            return PartialView("_WishList", model);
        }

        #endregion

        private async Task SendEmail(CheckoutViewModel model)
        {
            var content = GetEmailContent(model.Products);
            var email = new EmailModel
            {
                Subject = $"Đơn hàng {model.OrderNumber}",
                Content = content,
                RecipientEmail = model.Email,
                RecipientName = model.FullName,
                OrderId = model.Id
            };
            var result = await _emailService.SaveAsync(email);
            if(result.ResultType == Domain.Result.ResultType.Success)
            {
                //Send email to customer
                await _emailSender.SendEmailAsync(email.RecipientEmail, email.Subject, email.Content);

                //Send email to admin
                await _emailSender.SendEmailAsync(_appSettings.AdminEmails.Split(",").ToList(), email.Subject, email.Content);
            }
        }

        private string GetEmailContent(List<ProductCartViewModel> products)
        {
            var content = new StringBuilder();
            foreach(var item in products)
            {
                var sub = @$"<tr style='page-break-inside: avoid;'>
							<td width='204' align='center' style='border-top: 1px solid #000; padding: 13px 0;'>
								<strong style='font-family: Arial, sans-serif; font-size: 13px;'>
									[PRODUCT_NAME]
								</strong>
							</td>
							<td colspan='2' style='border-left: 1px solid #000; border-top: 1px solid #000; padding: 13px 15px; '>
								<span style='font-family: Arial, sans-serif; font-size: 13px;'>
									<strong>[PRODUCT_PRICE]</strong> x <strong>[PRODUCT_QUANTITY]</strong>
								</span>
							</td>
							<td colspan='3' style='border-left: 1px solid #000; border-top: 1px solid #000; padding: 13px 15px; '>
								<span style='font-family: Arial, sans-serif; font-size: 13px; white-space: nowrap;'>
									<strong>[PRODUCT_TOTAL]</strong>
								</span>
							</td>
						</tr>";
                content.Append(sub.Replace("[PRODUCT_NAME]", item.Name)
                    .Replace("[PRODUCT_PRICE]", item.Price.ToString("C0", System.Globalization.CultureInfo.CurrentCulture))
                    .Replace("[PRODUCT_QUANTITY]", item.Quantity.ToString())
                    .Replace("[PRODUCT_TOTAL]", (item.Quantity * item.Price).ToString("C0", System.Globalization.CultureInfo.CurrentCulture)));
            }

            var subTotal = @"<tr style='page-break-inside: avoid;'>
							<td colspan='3' width='104' align='center' style='border-top: 1px solid #000; padding: 13px 0;'>
								<strong style='font-family: Arial, sans-serif; font-size: 13px;'>
									Tổng cộng
								</strong>
							</td>
							<td colspan='3' style='border-left: 1px solid #000; border-top: 1px solid #000; padding: 13px 15px; '>
								<span style='font-family: Arial, sans-serif; font-size: 13px; white-space: nowrap;'>
									<strong>[ORDER_TOTAL]</strong>
								</span>
							</td>
						</tr>";
            content.Append(subTotal.Replace("[ORDER_TOTAL]", products.Sum(t => t.Price * t.Quantity).ToString("C0", System.Globalization.CultureInfo.CurrentCulture)));
            var body = @"<!DOCTYPE html>
<html>
<head>
    <meta http-equiv='Content-Type' content='text/html charset=UTF-8' />
</head>
<body style='margin: 0;'>
    <div style='font-family: Arial, sans-serif; font-size: 13px; color: #000;width: 650px; margin: 0 auto;'>
        <table border='0' align='center' cellpadding='0' cellspacing='0' style='width: 650px; margin: 0 auto; border-spacing: 0; background-color: white;'>
            <tr>
                <td>
                    <p style='font-family: Arial, sans-serif; font-size: 14px; line-height: 20px; margin: 0 0 20px 0;'>
                        <strong>Xin chào,</strong>
                    </p>
                    <p style='font-family: Arial, sans-serif; font-size: 14px;line-height: 20px; margin: 0 0 10px 0;'>
                        Cảm ơn bạn đã tin tưởng và ủng hộ chúng tôi. <br />
                        Chúng tôi sẽ liên hệ với bạn để xác nhận đơn hàng.
                    </p>
                    <p style='font-family: Arial, sans-serif; font-size: 14px;line-height: 20px; margin: 0 0 35px 0;'>
                        Nếu bạn có gì muốn tìm hiểu thêm, hãy liên hệ tới chúng tôi:
                        <a href='mailto:operationvn@ohmyhotel.com' style='color: #000; text-decoration: none'><span style='text-decoration: underline;'>admin@choquehuong.vn</span></a>
                    </p>
                </td>
            </tr>
            <tr>
                <td>
					<table border='0' cellpadding='0' cellspacing='0' style='height: 100%; width: 100%; border-spacing: 0; padding: 0; border-collapse: collapse; border: 1px solid #000;'>
						<tr style='page-break-inside: avoid;'>
							<td colspan='2' bgcolor='#f2f2f2' align='left' style='border-top: 1px solid #000; height: 40px; padding-left: 15px;'>
								<strong style='font-family: Arial, sans-serif; font-size: 14px;'>
								Đơn hàng
								</strong>
							</td>
							<td bgcolor='#f2f2f2' colspan='4' align='right' style='border-top: 1px solid #000; padding-right: 15px; '>
								
							</td>
						</tr>
						[CONTENT_EMAIL]
					</table>
                                        
				</td>
            </tr>
			<tr>
                <td align='center' style='font-family: Arial, sans-serif; color: #555; padding-bottom: 20px'></td>
            </tr>
            <tr>
                <td align='center' style='font-family: Arial, sans-serif; color: #555; padding-bottom: 10px'>Copyright &copy; choquehuong.vn</td>
            </tr>
        </table>
    </div>
</body>
</html>";
            return body.Replace("[CONTENT_EMAIL]", content.ToString());
        }
    }
}

Safira.App/Controllers/ProductController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Safira.Domain.Enums;
using Safira.Domain.IServices;
using Safira.Domain.Models;
using Safira.Domain.Models.Product;
using Safira.Domain.Result;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Safira.App.Controllers
{
    public class ProductController : ShoppingController
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IProductService _productService;
        private readonly IReviewService _reviewService;

        public ProductController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IProductService productService,
            IReviewService reviewService,
            ICartService cartService) : base(userManager,signInManager, productService, cartService)
        {
            _productService = productService;
            _userManager = userManager;
            _signInManager = signInManager;
            _reviewService = reviewService;
        }

        public async Task<IActionResult> Index(long id, string name="")
        {
            ViewBag.Menu = MenuEnum.Cuisine;
            var model = await _productService.GetByIdAsync(id);
            return View(model);
        }

        #region Shopping Cart

        [HttpGet]
        public async Task<IActionResult> QuickView(long id)
        {
            var model = await _productService.GetByIdAsync(id);
            return PartialView("_QuickView", model);
        }

        [HttpGet]
        public IActionResult GetShoppingCart()
        {
            var model = GetCart();
            return PartialView("_ShoppingCart", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(long id, int quantity = 1, bool replace = false)
        {
            var result = await AddCart(id, quantity, replace);
            return JsonResult(result);
        }

        [HttpPost]
        public IActionResult RemoveOutCart(long id)
        {
            var result = RemoveCart(id);
            return JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> GoToOrder(long id, int quantity = 1)
        {
            var result = new Result<bool>()
            {
                ResultType = ResultType.Success
            };
            var productInCart = GetCart();
            if (!productInCart.Any(t => t.ProductId == id))
            {
                await AddCart(id, quantity);
            }
            return JsonResult(result);
        }

        #endregion

        #region Favourite

        [HttpGet]
        public IActionResult GetFavourite()
        {
            var model = GetFavourites();
            return JsonResult(new Domain.Result.Result<int>
            {
                ResultType = Domain.Result.ResultType.Success,
                Value = model.Count
            });
            //return PartialView("_ShoppingCart", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddToFavourite(long id)
        {
            var result = await AddFavourite(id);
            return JsonResult(result);
        }

        [HttpPost]
        public IActionResult RemoveOutFavourite(long id)
        {
            var result = RemoveFavourite(id);
            return JsonResult(result);
        }

        #endregion

        [HttpPost]
        public async Task<IActionResult> AddReview(ReviewModel model)
        {
            var result = new Domain.Result.Result<int>()
            {
                ResultType = Domain.Result.ResultType.Error
            };
            if (ModelState.IsValid)
            {
                result = await _reviewService.SaveAsync(model);
            }
            return JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> GetReviewList(long id)
        {
            var model = await _reviewService.GetListAsync(id);
            return PartialView("_ReviewList", model);
        }

        public async Task<IActionResult> GetRelatedProduct(int id)
        {
            var products = await _productService.GetAllAsync(id);
            return PartialView("_RelatedProductList", products);
        }
    }
}

Safira.App/Areas/Admin/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.0.5
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

Safira.App/Areas/Admin/Views/Shared/_Header.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-controller="Home" asp-action="Index" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-controller="Order" asp-action="Index" class="nav-link">Đơn hàng</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-controller="Product" asp-action="Index" class="nav-link">Sản phẩm</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-controller="Category" asp-action="Index" class="nav-link">Nhóm sản phẩm</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-controller="Blog" asp-action="Index" class="nav-link">Cẩm nang</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/admin/img/user2-160x160.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/admin/img/user2-160x160.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/admin/img/user2-160x160.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

Safira.App/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/admin/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    @*<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">*@
    <link href="~/admin/dist/css/adminlte.min.css" rel="stylesheet" />
    <link href="~/plugins/summernote/summernote.min.css" rel="stylesheet" />
    <link href="~/plugins/toastr/toastr.css" rel="stylesheet" />
    <link href="~/admin/css/site.css" rel="stylesheet" />
    <link href="~/admin/lib/dropzone/dropzone.css" rel="stylesheet" />
    <link href="~/admin/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css" rel="stylesheet" />
    @*<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">*@
    <link href="~/admin/plugins/fontawesome-free/css/fontawesome.css" rel="stylesheet" />
    <link href="~/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.css" rel="stylesheet" />
    <link href="~/plugins/select2/css/select2.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    @*<script src="~/plugins/jquery/jquery.min.js"></script>*@
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/plugins/jquery-validation/additional-methods.min.js"></script>
    <script src="~/plugins/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/plugins/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <script src="~/admin/lib/dropzone/dropzone.js"></script>
    <script src="~/admin/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>

    <script src="~/admin/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/select2/js/select2.js"></script>
    <script src="~/admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.js"></script>
    <script src="~/admin/js/common/app.common.js"></script>
    <script src="~/admin/plugins/inputmask/jquery.inputmask.bundle.js"></script>
</head>
<body class="hold-transition sidebar-mini sidebar-collapse">
    <div class="wrapper">
        <partial name="_Header" />
        <partial name="_LeftMenu" />
        @RenderBody()
        <partial name="_Footer" />
    </div>
    <script src="~/admin/dist/js/adminlte.js"></script>
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    @*<script src="~/admin/dist/js/demo.js"></script>
        <script src="~/admin/js/common/app.common.js"></script>*@
    @RenderSection("Scripts", required: false)
    <script type="text/javascript">
        $.validator.setDefaults({
            ignore: ":hidden, [contenteditable='true']:not([name])"
        });
    </script>
</body>
</html>

Safira.App/Areas/Admin/Views/Shared/_LeftMenu.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a asp-action="" asp-controller="Home" class="brand-link">
        <img src="~/admin/img/AdminLTELogo.png"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Quản trị</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/admin/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a asp-action="Logout" asp-controller="Account" class="d-block">Tan Nguyen</a>
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a asp-controller="Home" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Trang chủ
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Order" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>
                            Đơn hàng
                            <span class="badge badge-danger right">6</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Product" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-tree"></i>
                        <p>
                            Sản phẩm
                            <span class="badge badge-success right">106</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Category" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Nhóm sản phẩm
                            <span class="badge badge-success right">10</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="User" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Thành viên
                            <span class="badge badge-warning right">500</span>
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>