Safira.App/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Safira.App.Extensions;
using Safira.Domain.Enums;
using Safira.Domain.IServices;
using Safira.Domain.Models;
using Safira.Domain.Models.Category;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Safira.App.Areas.Admin.Controllers
{
    public class CategoryController : BaseController
    {
        #region Fields & Ctor

        private readonly ICategoryService _categoryService;
        private readonly ApplicationSettings _appSettings;

        public CategoryController(
            ICategoryService categoryService,
            ApplicationSettings applicationSettings)
        {
            _categoryService = categoryService;
            _appSettings = applicationSettings;
        }

        #endregion

        #region Action Methods

        public async Task<ActionResult> Index()
        {
            var model = await GetListViewModel(new CategoryFilteringModel());
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            var model = new CategoryViewModel
            {
                Status = StatusEnum.Active.ToEnumSelectList(null, string.Empty),
                Categories = await _categoryService.GetSelectListAsync("Chọn nhóm"),
                Orders = GetSelectListOrder()
            };
            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var model = new CategoryViewModel
            {
                Status = StatusEnum.Active.ToEnumSelectList(null, string.Empty),
                Categories = await _categoryService.GetSelectListAsync("Chọn nhóm"),
                Orders = GetSelectListOrder(),
            };

            var category = await _categoryService.GetByIdAsync(id);
            if (category != null)
            {
                model.Id = category.Id;
                model.Name = category.Name;
                model.Description = category.Description;
                model.StatusId = category.StatusId;
                model.Order = category.Order;
                model.ParentId = category.ParentId;
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _categoryService.DeleteAsync(id);
            return JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> Save(CategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _categoryService.SaveAsync(model);
                return JsonResult(result);
            }
            return JsonError("Invalid model.");
        }

        [HttpGet]
        public async Task<IActionResult> GetList(CategoryFilteringModel filtering)
        {
            return PartialView("_CategoryList", await GetListViewModel(filtering));
        }

        #endregion

        #region Utilities Methods
        private async Task<CategoryListViewModel> GetListViewModel(CategoryFilteringModel filtering)
        {
            var categories = await _categoryService.GetListAsync(filtering);
            return new CategoryListViewModel(categories, filtering)
            {
                PageSizeOptions = _appSettings.PageSizeOptions.ToDicSelectList(filtering.PageSize.ToString(), false),
            };
        }

        private List<SelectListItem> GetSelectListOrder()
        {
            var orders = Enumerable.Range(1, 20)
                .Select(t => new SelectListItem { Text = t.ToString(), Value = t.ToString() })
                .ToList();
            return orders;
        }
        #endregion
    }
}

Safira.App/Areas/Admin/Views/Category/Create.cshtml
@model Safira.Domain.Models.Category.CategoryViewModel;
@{
    ViewData["Title"] = "Tạo nhóm sản phấm";
}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Tạo nhóm sản phẩm</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                        <li class="breadcrumb-item active"><a asp-controller="Category" asp-action="Index">Nhóm sản phẩm</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <!-- Main content -->
    <partial name="_CreateOrEdit" model="@Model" />
</div>

<script src="~/admin/js/pages/category.js" asp-append-version="true"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.textarea').summernote()
        CategoryModule.config({
            mode: AppCommon.ActionMode.Create,
            getListUrl: '@Url.Action("GetList", "Category")',
            viewListUrl: '@Url.Action("Index", "Category")'
        });
    });
</script>

Safira.App/Areas/Admin/Views/Category/Edit.cshtml
@model Safira.Domain.Models.Category.CategoryViewModel;
@{
    ViewData["Title"] = "Chỉnh sửa nhóm sản phấm";
}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Chỉnh sửa nhóm sản phẩm</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                        <li class="breadcrumb-item active"><a asp-controller="Category" asp-action="Index">Nhóm sản phẩm</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <!-- Main content -->
    <partial name="_CreateOrEdit" model="@Model" />
</div>

<script src="~/admin/js/pages/category.js" asp-append-version="true"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.textarea').summernote()
        CategoryModule.config({
            getListUrl: '@Url.Action("GetList", "Category")'
        });
    });
</script>

Safira.App/Areas/Admin/Views/Category/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Nhóm sản phẩm</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="" asp-controller="Home">Trang chủ</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <!-- Main content -->
    <section class="content" style="height:100%;">
        <div class="card dev-ajax-form">
            <div class="card-body p-0">
                <div class="box box-body no-border-top">
                    <form asp-action="GetList" asp-controller="Category" data-ajax="true" method="get"
                          data-ajax-mode="Replace" data-ajax-update="#dev-data-container"
                          data-ajax-complete="CategoryModule.OnGetDataComplete" data-ajax-begin="CategoryModule.OnGetDataBegin">
                        <div class="row">
                            <div class="col-12" id="dev-data-container">
                                <partial name="_CategoryList" model="Model" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>

<div class="modal fade dev-confirm-delete-modal">
    <div class="modal-dialog dev-ajax-form-2">
        <div class="modal-content">
            <form asp-action="Delete" asp-controller="Category" data-ajax="true" method="post"
                  data-ajax-complete="CategoryModule.OnDeleteComplete" data-ajax-begin="CategoryModule.OnDeleteBegin">
                <div class="modal-header">
                    <h4 class="modal-title">Xóa nhóm sản phẩm</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" />
                    <p>Bạn có chắc muốn xóa nhóm sản phẩm <i class="dev-delete-item-name text-danger"></i> không?</p>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-outline-info" data-dismiss="modal">Hủy</button>
                    <button type="submit" class="btn btn-outline-primary">Xóa</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/admin/js/common/pager.js"></script>
<script src="~/admin/js/pages/category.js" asp-append-version="true"></script>
<script type="text/javascript">
     $(document).ready(function () {
        CategoryModule.config({
            getListUrl: '@Url.Action("GetList", "Category")'
        });
    });
</script>

Safira.App/Areas/Admin/Views/Category/_CategoryList.cshtml
@using Safira.App.Extensions;
@using Safira.Domain.PagedList;
@model Safira.Domain.Models.Category.CategoryListViewModel


<div class="card-header">
    <div class="float-left">
        <div class="input-group input-group-sm" style="width: 150px;">
            <div class="input-group-append">
                <a asp-action="Create" asp-controller="Category" class="btn btn-outline-primary">
                    <i class="fas fa-plus"></i> Thêm mới
                </a>
            </div>
        </div>
    </div>
    <div class="float-right">
        <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="SearchKeyword" value="@Model.CurrentFiltering.SearchKeyword" class="form-control float-right" placeholder="Tìm kiếm">

            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-primary"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </div>
</div>
<!-- /.card-header -->
<div class="card-body table-responsive p-0">
    <table class="table table-bordered table-striped safira-table">
        <thead>
            <tr>
                <th style="width: 1%">
                    #
                </th>
                <th style="width: 20%">
                    @Html.RenderColumn("GetList", "Category", "Name", "Tên nhóm sản phẩm", null, null, Model.CurrentFiltering, string.Empty)
                </th>
                <th>
                    @Html.RenderColumn("GetList", "Category", "Description", "Mô tả", null, null, Model.CurrentFiltering, string.Empty)
                </th>
                <th style="width: 120px" class="text-center">
                    @Html.RenderColumn("GetList", "Category", "Status", "Trạng thái", null, null, Model.CurrentFiltering, string.Empty)
                </th>
                <th style="width:150px;" class="text-center">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Items.Any())
            {
                for (int i = 0; i < Model.Items.Count; i++)
                {
                    var item = Model.Items[i];
                    <tr>
                        <td>@(i + 1)</td>
                        <td>
                            <a asp-controller="client" asp-action="detail" asp-route-id="@item.Id">@item.Name</a>
                        </td>
                        <td>
                            @Html.Raw(item.Description)
                        </td>
                        <td class="text-center">
                            @((Safira.Domain.Enums.StatusEnum)item.StatusId)
                        </td>
                        <td class="project-actions text-right">
                            <a class="btn btn-outline-success btn-sm" title="Xem" href="#">
                                <i class="fas fa-folder">
                                </i>
                            </a>
                            <a class="btn btn-outline-warning btn-sm" title="Sửa" asp-action="Edit" asp-route-id="@item.Id">
                                <i class="fas fa-pencil-alt">
                                </i>
                            </a>
                            <a class="dev-delete-item-on-list btn btn-outline-danger btn-sm" title="Xóa" data-id="@item.Id" data-name="@item.Name" href="#">
                                <i class="fas fa-trash">
                                </i>
                            </a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5">No item to display</td>
                </tr>
            }

        </tbody>
    </table>
</div>
@if (Model.Items.Any())
{
    <div class="card-footer footer-table">
        <div class="float-left">
            Showing <i>@Model.Items.FirstItemOnPage-@Model.Items.LastItemOnPage</i> of <strong>@Model.Items.TotalItemCount</strong> Results | Show @Html.DropDownList("PageSize", Model.PageSizeOptions, null, new { @class = "select-no-search js-pager-pagesize", @data_formId = "#dev-client-list-form" }) entries
        </div>
        @if (Model.Items.PageCount > 1)
        {
            @Html.PagedListPager((IPagedList)Model.Items, page => Url.Action("GetList", "Category", values:
              new
              {
                  @PageNumber = page,
                  @PageSize = Model.CurrentFiltering.PageSize,
                  @SortBy = Model.CurrentFiltering.SortBy,
                  @SortDirection = Model.CurrentFiltering.SortDirection,
                  @SearchKeyword = Model.CurrentFiltering.SearchKeyword
              }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
              {
                  Display = PagedListDisplayMode.Always,
                  MaximumPageNumbersToDisplay = 5,
                  DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                  DisplayLinkToLastPage = PagedListDisplayMode.Always,
                  DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                  DisplayLinkToNextPage = PagedListDisplayMode.Always,
              }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "dev-data-container", OnComplete = "CategoryModule.OnGetListComplete", OnBegin = "CategoryModule.OnGetListBegin" }))
        }
    </div>
}

@*For sort*@
<input type="hidden" name="PageNumber" value="@Model.CurrentFiltering.PageNumber" />
<input type="hidden" name="SortBy" value="@Model.CurrentFiltering.SortBy" />
<input type="hidden" name="SortDirection" value="@Model.CurrentFiltering.SortDirection" />
<input type="hidden" name="SearchKeyword" value="@Model.CurrentFiltering.SearchKeyword" />

Safira.App/Areas/Admin/Views/Category/_CreateOrEdit.cshtml
@model Safira.Domain.Models.Category.CategoryViewModel;

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline dev-ajax-form">
                    <div class="card-header">
                        <h3 class="card-title">Nhóm sản phẩm <small></small></h3>
                    </div>
                    <form asp-action="Save" asp-controller="Category" data-ajax-method="POST" data-ajax="true"
                          data-ajax-begin="CategoryModule.OnSaveBegin" data-ajax-complete="CategoryModule.OnSaveComplete">
                        <div class="card-body">
                            <input type="hidden" asp-for="Id" />
                            <div class="form-group">
                                <label asp-for="Name">Tên nhóm sản phẩm</label>
                                <input type="text" asp-for="Name" class="form-control" placeholder="Nhập tên sản phẩm">
                                <span asp-validation-for="Name"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description">Mô tả</label>
                                <div class="mb-3">
                                    <textarea asp-for="Description" class="textarea" placeholder=""
                                              style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- select -->
                                    <div class="form-group">
                                        <label>Trạng thái</label>
                                        <safira-select asp-items="Model.Status"
                                                       asp-for-name="StatusId" class="custom-select" />
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>Nhóm</label>
                                        <safira-select asp-items="Model.Categories"
                                                       asp-for-name="ParentId" class="custom-select" />
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label>Sắp xếp</label>
                                        <safira-select asp-items="Model.Orders"
                                                       asp-for-name="Order" class="custom-select" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-outline-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-6">
            </div>
        </div>
    </div>
</section>